services:
  - type: web
    name: bmz-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    disk:
      name: bmz-storage
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: TRANSCRIPTION_API_KEY
        sync: false 
    branch: main